### ISSUE TITLE
ImmersiveEngineering model render

### ISSUE THREAD

**Issue by Mudresistor** [gamerforEA/MineTuner#1]
Some users got a crash during initialisation, like this:

> [11:16:54] [Client thread/INFO] [ImmersiveEngineering]: Attempting to extend PotionArray by 4 
[OptiFine] Loading texture map: textures/revolvers 
[OptiFine] Texture size: textures/revolvers, 16x16 
[11:16:55] [Client thread/INFO]: Created: 16x16 textures/revolvers-atlas 
[SMC INF]allocateTextureMap 94 0 16 16 1.0 
[SMC WARNING]bad vertexCount

And some also have no models of machines, or just texture-mapping, or smth like:
[this](https://media.discordapp.net/attachments/504285142102310931/607118875061911552/unknown.png?width=1191&height=670)

**Comment by Mudresistor** [comment]
And also problems with model-rendering in thaumcraft Thaumonomicon GUi that causes crash

> java.lang.NullPointerException: Rendering item


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at thaumcraft.client.gui.GuiResearchBrowser.genResearchBackground(GuiResearchBrowser.java:612)

-- Item being rendered --
Details:
	Item Type: net.minecraft.item.ItemBlock@4e79c8ef
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at thaumcraft.client.gui.GuiResearchBrowser.genResearchBackground(GuiResearchBrowser.java:612)
	at thaumcraft.client.gui.GuiResearchBrowser.func_73863_a(GuiResearchBrowser.java:280)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1397)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
