### ISSUE TITLE
NPE Automagy renderer crash

### ISSUE THREAD

**Issue by Mudresistor** [gamerforEA/MineTuner#2]
> java.lang.NullPointerException: Rendering Block Entity
	at com.gamerforea.minetuner.client.model.DisplayListedWavefrontObject.renderPart(DisplayListedWavefrontObject.java:89)
	at com.gamerforea.minetuner.client.model.DisplayListedWavefrontObject.renderOnly(DisplayListedWavefrontObject.java:73)
	at tuhljin.automagy.renderers.BlockHourglassRenderer.func_147500_a(BlockHourglassRenderer.java:110)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:772)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1596)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1330)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by gamerforEA** [comment]
Fixed: https://github.com/gamerforEA/MineTuner/commit/a525379f0a9b0d3e0d2581a56c11516a699a9316
